// Auto-generated by: pnpm db:types
// Run `pnpm db:types` after any schema change to regenerate

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id:                 string;
          email:              string;
          name:               string | null;
          preferred_language: string;
          credit_balance:     number;
          stripe_customer_id: string | null;
          created_at:         string;
          updated_at:         string;
        };
        Insert: Omit<Database["public"]["Tables"]["users"]["Row"], "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["users"]["Insert"]>;
      };
      contracts: {
        Row: {
          id:                  string;
          user_id:             string | null;
          file_name:           string | null;
          storage_path:        string | null;
          extracted_text_hash: string | null;
          language:            string;
          analysis:            Json | null;
          status:              "pending" | "done" | "error";
          ip_hash:             string | null;
          created_at:          string;
        };
        Insert: Omit<Database["public"]["Tables"]["contracts"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["contracts"]["Insert"]>;
      };
      payments: {
        Row: {
          id:                 string;
          user_id:            string | null;
          stripe_session_id:  string;
          stripe_customer_id: string | null;
          amount_cents:       number;
          credits_granted:    number;
          plan:               string | null;
          created_at:         string;
        };
        Insert: Omit<Database["public"]["Tables"]["payments"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["payments"]["Insert"]>;
      };
      email_log: {
        Row: {
          id:          string;
          email_hash:  string;
          resend_id:   string | null;
          contract_id: string | null;
          status:      string;
          language:    string | null;
          sent_at:     string;
        };
        Insert: Omit<Database["public"]["Tables"]["email_log"]["Row"], "id" | "sent_at">;
        Update: Partial<Database["public"]["Tables"]["email_log"]["Insert"]>;
      };
    };
    Functions: {
      add_credits:   { Args: { uid: string; amount: number }; Returns: void };
      deduct_credit: { Args: { uid: string };                 Returns: void };
    };
  };
}
