import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Contrivox",
  description: "Terms governing your use of the Contrivox contract analysis service.",
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "May 20, 2026";
const CONTACT_EMAIL = "legal@contrivox.com";
const SUPPORT_EMAIL = "support@contrivox.com";

export default function TermsPage() {
  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Fraunces:wght@400;600;700&family=DM+Sans:wght@400;500;600&display=swap');
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #07070f; color: rgba(255,255,255,0.82); font-family: 'DM Sans', sans-serif; }
        a { color: #a78bfa; text-decoration: none; }
        a:hover { text-decoration: underline; }
      `}</style>

      <div style={{ minHeight: "100vh", background: "#07070f" }}>
        {/* Nav */}
        <nav style={{ borderBottom: "0.5px solid rgba(255,255,255,0.08)", padding: "0 20px" }}>
          <div style={{ maxWidth: 760, margin: "0 auto", display: "flex", alignItems: "center", height: 56 }}>
            <Link href="/" style={{ display: "flex", alignItems: "center", gap: 8, textDecoration: "none" }}>
              <div style={{ width: 28, height: 28, background: "linear-gradient(135deg,#7c3aed,#4f46e5)", borderRadius: 7, display: "flex", alignItems: "center", justifyContent: "center" }}>
                <svg width="16" height="16" viewBox="0 0 18 18" fill="none"><path d="M3 5h12M3 9h7M3 13h9" stroke="white" strokeWidth="1.6" strokeLinecap="round"/></svg>
              </div>
              <span style={{ fontFamily: "'Fraunces',serif", fontSize: 17, color: "white", fontWeight: 600 }}>Contrivox</span>
            </Link>
          </div>
        </nav>

        {/* Important disclaimer banner */}
        <div style={{ background: "rgba(239,68,68,0.07)", borderBottom: "0.5px solid rgba(239,68,68,0.18)", padding: "12px 20px" }}>
          <p style={{ maxWidth: 760, margin: "0 auto", fontSize: 13, color: "#f87171", fontFamily: "'DM Sans',sans-serif", textAlign: "center", lineHeight: 1.5 }}>
            <strong>Contrivox is not a law firm and does not provide legal advice.</strong> Analysis reports are for informational purposes only. Always consult a licensed attorney before acting on any contract.
          </p>
        </div>

        {/* Content */}
        <main style={{ maxWidth: 760, margin: "0 auto", padding: "52px 20px 80px" }}>
          <p style={{ fontSize: 11, color: "rgba(255,255,255,0.3)", letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 14, fontFamily: "'DM Sans',sans-serif" }}>
            Legal
          </p>
          <h1 style={{ fontFamily: "'Fraunces',serif", fontSize: "clamp(28px,5vw,44px)", color: "white", marginBottom: 10, lineHeight: 1.1, fontWeight: 600 }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: 13, color: "rgba(255,255,255,0.35)", marginBottom: 48, fontFamily: "'DM Sans',sans-serif" }}>
            Last updated: {LAST_UPDATED}
          </p>

          <Section title="1. Acceptance of Terms">
            <P>By accessing or using Contrivox at contrivox.com (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service. These Terms apply to all visitors, users, and others who access or use the Service.</P>
            <P>You must be at least 18 years old to use Contrivox. By using the Service you represent that you meet this requirement.</P>
          </Section>

          <Section title="2. Description of Service">
            <P>Contrivox uses artificial intelligence (specifically Anthropic's Claude) to help users understand the language, risks, and implications of legal contracts. The Service produces a plain-language analysis that includes: a fairness score, identified clauses, red flags, missing protections, and suggested negotiation language.</P>
            <P>The Service is an educational and informational tool only. It does not constitute legal advice, legal counsel, or the practice of law.</P>
          </Section>

          <Section title="3. Not Legal Advice — Critical Disclaimer">
            <Callout>
              <p style={{ fontSize: 15, fontWeight: 700, color: "#f87171", marginBottom: 8, fontFamily: "'DM Sans',sans-serif" }}>Contrivox is not a law firm. We are not your lawyer.</p>
              <P>Analysis reports generated by Contrivox are produced by artificial intelligence and are provided for informational and educational purposes only. They do not constitute legal advice, legal opinions, or legal representation, and no attorney-client relationship is formed between you and Contrivox.</P>
              <P>AI-generated analysis may be incomplete, inaccurate, outdated, or inapplicable to your specific situation. Legal issues are highly fact-specific and jurisdiction-dependent. Always consult a licensed attorney in your jurisdiction before signing any contract, refusing to sign, or relying on any information provided by Contrivox.</P>
            </Callout>
          </Section>

          <Section title="4. User Responsibilities">
            <P>By using Contrivox, you represent and warrant that:</P>
            <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
              {[
                "You have the right to upload and analyse the contract you submit (e.g., it is yours, you have the other party's consent, or it is not subject to a confidentiality restriction that prohibits third-party review)",
                "You will not upload contracts containing third-party personal data (such as names, SSNs, addresses) beyond what is necessary for analysis",
                "You will not use the Service to analyse contracts for illegal purposes",
                "You will not attempt to reverse-engineer, scrape, or misuse the Service",
                "You will not impersonate any person or entity or misrepresent your affiliation",
              ].map((item, i) => (
                <li key={i} style={{ fontSize: 15, color: "rgba(255,255,255,0.68)", lineHeight: 1.7, fontFamily: "'DM Sans',sans-serif" }}>{item}</li>
              ))}
            </ul>
          </Section>

          <Section title="5. Payments and Refunds">
            <SubSection title="5.1 Pricing">
              <P>Contrivox offers a free preview of your analysis and a one-time payment to unlock the full report. Prices are displayed in US Dollars (USD) and are inclusive of all applicable taxes where required by law. We reserve the right to change pricing with reasonable notice.</P>
            </SubSection>
            <SubSection title="5.2 One-Time Purchase">
              <P>Full reports are sold as one-time digital purchases. There are no recurring charges unless you explicitly purchase a subscription or credits package. Payment is processed securely by Stripe.</P>
            </SubSection>
            <SubSection title="5.3 Refund Policy">
              <P>Because Contrivox delivers digital content (the full analysis report) immediately upon payment, we generally do not offer refunds once the report has been delivered to your email. However, if you experience a technical issue that prevented delivery of your report, contact <A href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</A> within 7 days and we will investigate and remedy the situation, which may include a redelivery or full refund at our discretion.</P>
            </SubSection>
          </Section>

          <Section title="6. Your Content">
            <P>You retain all rights to the contract documents you upload. By uploading a contract, you grant Contrivox a limited, temporary licence to transmit and process the document solely for the purpose of generating your analysis. This licence terminates when the analysis is complete and the file is deleted from our systems (within 30 days).</P>
            <P>We do not claim ownership of your documents and do not use them to train AI models.</P>
          </Section>

          <Section title="7. Intellectual Property">
            <P>The Contrivox name, logo, website design, software, and analysis framework are owned by Contrivox and protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works from our Service without our express written permission.</P>
            <P>Analysis reports delivered to you are licensed for your personal use only. You may not resell, sublicense, or commercially exploit the reports without our written consent.</P>
          </Section>

          <Section title="8. Prohibited Uses">
            <P>You may not use Contrivox to:</P>
            <ul style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 8 }}>
              {[
                "Violate any applicable law or regulation",
                "Analyse documents that contain classified or government-protected information",
                "Systematically harvest or scrape data from the Service",
                "Circumvent rate limits or security measures",
                "Upload malicious files or attempt to compromise our systems",
                "Resell or sublicense access to the Service without authorisation",
                "Use the Service to provide legal advice to others for compensation without a law licence",
              ].map((item, i) => (
                <li key={i} style={{ fontSize: 15, color: "rgba(255,255,255,0.68)", lineHeight: 1.7, fontFamily: "'DM Sans',sans-serif" }}>{item}</li>
              ))}
            </ul>
          </Section>

          <Section title="9. Disclaimer of Warranties">
            <Callout>
              <P>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI-GENERATED ANALYSES WILL BE ACCURATE OR COMPLETE.</P>
              <P>AI models can produce incorrect, outdated, or misleading output. We expressly disclaim any warranty regarding the accuracy, completeness, or suitability of any analysis for any particular legal purpose.</P>
            </Callout>
          </Section>

          <Section title="10. Limitation of Liability">
            <Callout>
              <P>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CONTRIVOX SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES — INCLUDING LOST PROFITS, LOSS OF DATA, OR HARM FROM RELIANCE ON AN AI-GENERATED ANALYSIS — ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.</P>
              <P>IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID CONTRIVOX IN THE 12 MONTHS PRECEDING THE CLAIM, OR (B) $10 USD.</P>
              <P>Some jurisdictions do not allow the exclusion or limitation of certain warranties or liability. In such jurisdictions, our liability will be limited to the greatest extent permitted by law.</P>
            </Callout>
          </Section>

          <Section title="11. Indemnification">
            <P>You agree to indemnify, defend, and hold harmless Contrivox and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising out of or in any way connected with: (a) your access to or use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights; or (d) any claim that your submitted content caused damage to a third party.</P>
          </Section>

          <Section title="12. Privacy">
            <P>Your use of the Service is also governed by our <A href="/privacy">Privacy Policy</A>, which is incorporated into these Terms by reference. Please review it carefully to understand how we collect, use, and disclose information about you.</P>
          </Section>

          <Section title="13. Third-Party Services">
            <P>The Service integrates with third-party services including Stripe (payments), Anthropic (AI analysis), and Supabase (infrastructure). Your use of these services is subject to their respective terms and privacy policies. We are not responsible for the practices of these third parties.</P>
          </Section>

          <Section title="14. Modifications to the Service">
            <P>We reserve the right to modify, suspend, or discontinue the Service (or any part thereof) at any time with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Service.</P>
          </Section>

          <Section title="15. Changes to These Terms">
            <P>We may revise these Terms from time to time. When we do, we will update the "Last updated" date. Material changes will be communicated via the website. Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms.</P>
          </Section>

          <Section title="16. Governing Law and Disputes">
            <P>These Terms are governed by the laws of the State of Delaware, United States, without regard to its conflict-of-law provisions. Any dispute arising from or relating to these Terms or the Service shall be resolved exclusively in the state or federal courts located in Delaware, and you consent to personal jurisdiction in those courts.</P>
            <P>Before initiating any formal legal proceeding, you agree to contact us at <A href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</A> and provide a written description of the dispute. We will attempt to resolve disputes informally within 30 days of receiving written notice.</P>
          </Section>

          <Section title="17. Severability">
            <P>If any provision of these Terms is found to be unenforceable or invalid, that provision will be modified to the minimum extent necessary to make it enforceable, and the remaining provisions will continue in full force and effect.</P>
          </Section>

          <Section title="18. Contact">
            <P>Questions about these Terms should be directed to:</P>
            <div style={{ background: "rgba(255,255,255,0.04)", border: "0.5px solid rgba(255,255,255,0.08)", borderRadius: 10, padding: "16px 18px", marginTop: 12 }}>
              <p style={{ fontSize: 14, color: "rgba(255,255,255,0.7)", fontFamily: "'DM Sans',sans-serif", lineHeight: 1.7 }}>
                Contrivox<br/>
                Legal: <A href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</A><br/>
                Support: <A href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</A>
              </p>
            </div>
          </Section>

          <div style={{ marginTop: 48, paddingTop: 24, borderTop: "0.5px solid rgba(255,255,255,0.08)", display: "flex", gap: 24, flexWrap: "wrap" }}>
            <Link href="/privacy" style={{ fontSize: 13, color: "rgba(255,255,255,0.35)" }}>Privacy Policy</Link>
            <Link href="/" style={{ fontSize: 13, color: "rgba(255,255,255,0.35)" }}>← Back to Contrivox</Link>
          </div>
        </main>
      </div>
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{ fontFamily: "'Fraunces',serif", fontSize: 20, color: "white", marginBottom: 14, fontWeight: 600 }}>{title}</h2>
      <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>{children}</div>
    </section>
  );
}

function SubSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 style={{ fontSize: 14, fontWeight: 600, color: "rgba(255,255,255,0.6)", marginBottom: 8, fontFamily: "'DM Sans',sans-serif" }}>{title}</h3>
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>{children}</div>
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p style={{ fontSize: 15, color: "rgba(255,255,255,0.68)", lineHeight: 1.75, fontFamily: "'DM Sans',sans-serif" }}>{children}</p>
  );
}

function A({ href, children }: { href: string; children: React.ReactNode }) {
  return <a href={href} style={{ color: "#a78bfa" }}>{children}</a>;
}

function Callout({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ background: "rgba(239,68,68,0.05)", border: "0.5px solid rgba(239,68,68,0.18)", borderRadius: 10, padding: "16px 18px", display: "flex", flexDirection: "column", gap: 10 }}>
      {children}
    </div>
  );
}
